project:
  type: book
  output-dir: docs

book:
  title: "CSC 477 - Group 4"
  author: "Chris Jacob"
  date: "8/31/2024"
  chapters:
    - index.qmd
    - part: "Final Project"
      chapters:
        - diego_final.qmd
        - samuel_final.qmd
        - janice_final.qmd
        - chris_final.qmd
    - part: "Midterm"
      chapters: 
        - diego.qmd
        - samuel.qmd
        - janice.qmd
        - chris.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


jupyter: python3
